#:kivy 2.2.1
#:include select_point_screen.kv
#:include threshholdscreen.kv
#:include draw_border_screen.kv
#:include choose_image_screen.kv
#:include select_plate_screen.kv
#:include log_length_screen.kv
#:include stack_volume_screen.kv

Screens:
    ChooseImageScreen:
    DrawBorderScreen:
    SelectPlateScreen:
    SelectPointScreen:
    ThreshholdScreen:
    LogLengthScreen:
    StackVolumeScreen: